language: python
python:
  - "3.5"

before_install:
  - nvm install 6.10.2

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - python -m nltk.downloader $(tr "\n" " " < ".nltk_packages")
  - pip install coveralls

script:
  - flake8
  - pytest --cov
  - eslint static/js/app/**/*.es6

after_success:
  - coveralls
